# app/migrations/script.py.mako

"""add profiles table

Revision ID: 170a1851acc4
Revises: d34faed89165
Create Date: 2026-07-01 21:42:34.259841

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '170a1851acc4'
down_revision: Union[str, None] = 'd34faed89165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_s3_key', sa.String(length=500), nullable=True),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###