# app/migrations/script.py.mako

"""add sharing tables

Revision ID: 6a4f7fb2326f
Revises: dd62be4ab5d2
Create Date: 2026-07-02 21:48:03.439135

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6a4f7fb2326f'
down_revision: Union[str, None] = 'dd62be4ab5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_id != blocked_id', name='no_self_block'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('share_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_clusters_sender_id'), 'share_clusters', ['sender_id'], unique=False)
    op.create_table('share_cluster_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('media_file_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['share_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_cluster_files_cluster_id'), 'share_cluster_files', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_share_cluster_files_media_file_id'), 'share_cluster_files', ['media_file_id'], unique=False)
    op.create_table('share_cluster_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_by_recipient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['share_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_cluster_recipients_cluster_id'), 'share_cluster_recipients', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_share_cluster_recipients_recipient_id'), 'share_cluster_recipients', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_cluster_recipients_recipient_id'), table_name='share_cluster_recipients')
    op.drop_index(op.f('ix_share_cluster_recipients_cluster_id'), table_name='share_cluster_recipients')
    op.drop_table('share_cluster_recipients')
    op.drop_index(op.f('ix_share_cluster_files_media_file_id'), table_name='share_cluster_files')
    op.drop_index(op.f('ix_share_cluster_files_cluster_id'), table_name='share_cluster_files')
    op.drop_table('share_cluster_files')
    op.drop_index(op.f('ix_share_clusters_sender_id'), table_name='share_clusters')
    op.drop_table('share_clusters')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###