# app/migrations/script.py.mako

"""add media_files table

Revision ID: dd62be4ab5d2
Revises: b244517baa2a
Create Date: 2026-07-02 11:49:01.134830

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dd62be4ab5d2'
down_revision: Union[str, None] = 'b244517baa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###